### PR TITLE
First pass at reimann conversion

### PR DESCRIPTION
**Pull request by simpsora**
Switch from StatsD to the Riemann java client

/cc @gstamp

### CODE REVIEW

**Comment by gstamp** [comment]
spaces > tabs

**Comment by gstamp** [comment]
An alternative to this might have been to use https://github.com/joshgummersall/statsd-riemann-backend to push info from statsd to riemann.

**Comment by gstamp** [comment]
Or https://github.com/simao/riepete

**Comment by gstamp** [comment]
:+1: PR seems fine.

**Comment by simpsora** [comment]
Closing, I don't think we'll be using this.

**Pull request closed without merging**
